project/urls.py
from django.contrib import admin
from django.urls import path, include
from courses import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main, name='home'),
    path('home/', views.main, name='home'),
    path('categories/<int:id>', views.categories, name='categories'),
    path('list/<int:id>', views.list, name='list'), 
    path('statistic/', views.statistic, name='statistic'), 
    path('workspace/', include('workspace.urls')), 

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

workspace/urls.py
from django.urls import path
from workspace import views

urlpatterns = [
    path('change_profile/', views.change_profile, name='change_profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('logout_prof/', views.logout_prof, name='logout_prof'),
    path('registration/', views.registration_prof, name='registration'),
    path('login/', views.login_prof, name='login'),
    path('create/', views.create, name='create'),
    path('update/<int:id>', views.update, name='update'),
    path('delete/<int:id>', views.delete, name='delete'),
    path('', views.main, name='workspace'),
]

courses/models.py
from django.db import models
from django_resized import ResizedImageField
from django.contrib.auth.models import User

class Courses(models.Model):
    title = models.CharField('Название', max_length=30)
    photo = models.ImageField('Фото', upload_to='imgs/')
    category = models.ForeignKey('Category', on_delete=models.CASCADE, related_name='courses', verbose_name='Категория')
    description = models.TextField('Описание', max_length=120)
    price = models.IntegerField('Цена')
    type_of_training = models.ForeignKey('TypeOfTraining', on_delete=models.PROTECT, related_name='courses', verbose_name='Тип обучения')
    school = models.ForeignKey('School', on_delete=models.PROTECT, related_name='courses', verbose_name='Школа')
    type_of_courses = models.ForeignKey('TypeOfCourses', on_delete=models.PROTECT, related_name='courses', verbose_name='Тип курса')
    duration = models.ForeignKey('Duration', on_delete=models.PROTECT, related_name='courses', verbose_name='Продолжитeльность')
    residence = models.ForeignKey('Residence', on_delete=models.PROTECT, related_name='courses', verbose_name='Проживание')
    date = models.DateField('Дата добовения', auto_now_add=True)
    is_publish = models.BooleanField('Публичность', default=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор')
    views = models.PositiveIntegerField('Просмотры', default=0)

    def __str__(self):
        return f'{self.title}'
    
    def averge_retings(self):
        ratings = self.retings.all()
        if ratings:
            return sum([rating.score for rating in ratings]) / len(ratings)
        return 0
    
class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey('Courses', on_delete=models.CASCADE)
    text = models.TextField('Текстовый комментарий', max_length=500)
    created = models.DateTimeField('Добавлен', auto_now_add=True)
    moder = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f'{self.user}  {self.course}'
    
class Retings(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey('Courses', related_name='retings', on_delete=models.CASCADE)
    score = models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])

    def __str__(self):
        return f"{self.score} by {self.user.username} for {self.course.title}"
    
class Category(models.Model):
    title = models.CharField('Категория', max_length=20)
    def __str__(self):
        return f'{self.title}'
    
class ImgAttribute(models.Model):
    product = models.ForeignKey('Courses', on_delete=models.CASCADE, related_name='imgs', verbose_name='Связь')
    image = ResizedImageField('изображение', upload_to='product_images/')
    def __str__(self) -> str:
        return f'{self.product}'
    
class TypeOfTraining(models.Model):
    title = models.CharField('Название', max_length=10)

    def __str__(self) -> str:
        return f'{self.title}'
    

class School(models.Model):
    title = models.CharField('Название', max_length=10)

    def __str__(self) -> str:
        return f'{self.title}'
    

class TypeOfCourses(models.Model):
    title = models.CharField('Название', max_length=10)

    def __str__(self) -> str:
        return f'{self.title}'
    

class Duration(models.Model):
    title = models.CharField('Название', max_length=10)

    def __str__(self) -> str:
        return f'{self.title}'
    
class Residence(models.Model):
    title = models.CharField('Название', max_length=10)

    def __str__(self) -> str:
        return f'{self.title}'
    

workspace/views.py
from django.shortcuts import render, redirect
from courses.models import Category, Courses
from courses.filter import SearchFilter
from django.core.paginator import Paginator
from workspace.forms import CreateForms, UpdateForms, RegistrationForm,LoginForms, ChangePasswordForm, ChangeProfileForm
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from .decorators import _login_required, is_owner


@_login_required
def main(request):
    categorys = Category.objects.all()
    page_obj = Courses.objects.filter(author=request.user).order_by('views')
    filter_set = SearchFilter(request.GET, queryset=page_obj)
    page_obj = filter_set.qs

    return render(request, 'workspace/body.html', {'categorys':categorys, 'page_obj':page_obj, 'filter_set':filter_set})

@_login_required
def create(request):
    courses = Courses.objects.all()
    categorys = Category.objects.all()
    if request.method == 'POST':
        form = CreateForms(data=request.POST, files=request.FILES)
        if form.is_valid():
            courses = form.save(commit=False)
            courses.author = request.user
            courses.save()
            messages.success(request, f'Вы создали курс {courses.title}')
            return redirect('/workspace/')
    else:
        form = CreateForms()

    return render(request, 'workspace/create.html', {'categorys':categorys, 'form':form})

@_login_required
@is_owner
def update(request, id):
    courses = Courses.objects.get(id=id)
    categorys = Category.objects.all()

    if request.method == 'POST':
        form = UpdateForms(data=request.POST, files=request.FILES, instance=courses)
        if form.is_valid():
            form.save()
            messages.success(request, f'Вы успешно обновили {courses.category} {courses.title}')
            return redirect('/workspace/')
    else:
        form = UpdateForms(instance=courses)


    return render(request, 'workspace/update.html',  {'categorys':categorys, 'form':form, 'courses':courses})

@_login_required
@is_owner
def delete(request, id):
    courses = Courses.objects.get(id=id)
    name = courses.title
    courses.delete()
    messages.error(request, f'Вы удалили курс {name}')

    return redirect('/workspace/')



def registration_prof(request):
    categorys = Category.objects.all()

    form = RegistrationForm()
    if request.method == 'POST':
        form = RegistrationForm(data=request.POST)
        if form.is_valid():
            user1 = form.save()
            login(request, user1)
            messages.success(request, f'Вы успшно создали аккаунт')
            return redirect('/workspace/')

    return render(request, 'auth/register.html', {'form':form, 'categorys':categorys})

def login_prof(request):
    categorys = Category.objects.all()

    form= LoginForms()
    if request.method == 'POST':
        form = LoginForms(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)

            if user:
                login(request, user)
                messages.success(request, f'Добро пожаловать {username}')
                return redirect('/workspace/')
            
            messages.error(request, 'Акаунт не найден (')

    return render(request, 'auth/login.html', {'form':form, 'categorys':categorys})

def logout_prof(request):
    if request.user.is_authenticated:
        logout(request)

    return redirect('/home/')


@_login_required
def change_password(request):
    categorys = Category.objects.all()

    form = ChangePasswordForm()
    if request.method == 'POST':
        form = ChangePasswordForm(data=request.POST, user=request.user)
        if form.is_valid():
            new_pass = form.cleaned_data.get('password_upd1')
            user = request.user
            user.set_password(new_pass)
            user.save()
            login(request, user)
            messages.success(request, f'Успешно изменен пароль {user.username}')

            return redirect('/workspace/')
    print(form.errors)


    return render(request, 'auth/change_password.html', {'form':form, 'categorys':categorys})

@_login_required
def change_profile(request):
    categorys = Category.objects.all()

    form = ChangeProfileForm(instance=request.user)
    if request.method == 'POST':
        form = ChangeProfileForm(data=request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, f'Ваш профиль успешно изменен')
            return redirect('/workspace/')

    return render(request, 'auth/change_profile.html', {'form':form, 'categorys':categorys})

templates/workspace/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Workspace</title>
    <script src="https://cdn.tailwindcss.com"></script>
    {% block links %}{% endblock links %}
</head>
<body>
    {% include "components/first_nav.html" %}
    {% include "components/messages.html" %}
    {% block creat %}
        {% block search %}{% endblock search %}
        {% include "components/catalog.html" %}
    {% endblock creat %}
    {% block update %}{% endblock update %}
    {% include "components/footer.html" %}
</body>
</html>

templates/workspace/body.html
{% extends "workspace/base.html" %}
{% load static %}

{% block links %}
<link rel="stylesheet" href="{% static "../static/css/workspace/cards.css" %}">
{% endblock links %}

{% block search %}
    <div class="back-search">
        <div class="container">
            <div class="search">
                <form action="" method='GET' class='form-search'>
                    {{filter_set.form.as_p}}
                    <div class='flex items-center'>
                        <button type='submit' class='btn-search'><img src="{% static "../static/img/Icon.png" %}" class='btn-search2' alt=""><h3 class='h3-btn'>Поиск</h3></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock search %}





templates/workspace/create.html
{% extends "workspace/base.html" %}

{% load static %}


{% block creat %}
    <div class="container">
        <div class='flex items-center justify-center mt-5 mb-[50px]'>
            <form action="{% url 'create' %}" method="POST" enctype="multipart/form-data" class='w-full max-w-2xl bg-white p-8 rounded-lg shadow-lg' novalidate>
              {% csrf_token %}
              <h2 class="text-2xl font-bold text-center text-gray-700 mb-6">Создание</h2>
              <div>
                <label for="id_title" >{{form.title.label}}</label>
                {{form.title}}
                <div class="text-danger">
                  {% for error in form.title.errors %}
                      <div class='text-red-500'>{{ error }}</div>
                  {% endfor %}
                </div>
              </div>
        
              <div>
                <label for="id_photo">{{form.photo.label}}</label>
                {{form.photo}}
                <div class="text-danger">
                  {% for error in form.photo.errors %}
                      <div class='text-red-500'>{{ error }}</div>
                  {% endfor %}
                </div>
              </div>
        
              <div>
                <label for="id_category">{{form.category.label}}</label>
                {{form.category}}
                <div class="text-danger">
                  {% for error in form.category.errors %}
                      <div class='text-red-500'>{{ error }}</div>
                  {% endfor %}
                </div>
              </div>
        
              <div>
                <label for="id_description">{{form.description.label}}</label>
                {{form.description}}
                <div class="text-danger">
                  {% for error in form.description.errors %}
                      <div class='text-red-500'>{{ error }}</div>
                  {% endfor %}
                </div>
              </div>
        
              <div>
                <label for="id_price">{{form.price.label}}</label>
                {{form.price}}
                <div class="text-danger">
                  {% for error in form.price.errors %}
                      <div class='text-red-500'>{{ error }}</div>
                  {% endfor %}
                </div>
              </div>
        
              <div>
                <label for="id_type_of_training">{{form.type_of_training.label}}</label>
                {{form.type_of_training}}
                <div class="text-danger">
                  {% for error in form.type_of_training.errors %}
                      <div class='text-red-500'>{{ error }}</div>
                  {% endfor %}
                </div>
              </div>
        
              <div>
                <label for="id_school">{{form.school.label}}</label>
                {{form.school}}
                <div class="text-danger">
                  {% for error in form.school.errors %}
                      <div class='text-red-500'>{{ error }}</div>
                  {% endfor %}
                </div>
              </div>
        
              <div>
                <label for="id_type_of_courses">{{form.type_of_courses.label}}</label>
                {{form.type_of_courses}}
                <div class="text-danger">
                  {% for error in form.type_of_courses.errors %}
                      <div class='text-red-500'>{{ error }}</div>
                  {% endfor %}
                </div>
              </div>
        
              <div>
                <label for="id_duration">{{form.duration.label}}</label>
                {{form.duration}}
                <div class="text-danger">
                  {% for error in form.duration.errors %}
                      <div class='text-red-500'>{{ error }}</div>
                  {% endfor %}
                </div>
              </div>
        
              <div>
                <label for="id_residence">{{form.residence.label}}</label>
                {{form.residence}}
                <div class="text-danger">
                  {% for error in form.residence.errors %}
                      <div class='text-red-500'>{{ error }}</div>
                  {% endfor %}
                </div>
              </div>
        
              <div class='mb-[20px]'>
                <label for="id_is_publish">{{form.is_publish.label}}</label>
                {{form.is_publish}}
                <div class="text-danger">
                  {% for error in form.is_publish.errors %}
                      <div class='text-red-500'>{{ error }}</div>
                  {% endfor %}
                </div>
              </div>
        
              <button type="submit" class="w-full py-3 bg-[#4361EE] text-white font-semibold rounded-lg hover:bg-[#4361EE] focus:outline-none focus:ring-2 focus:ring-black focus:ring-offset-2">Создать</button>
            </form>
          </div>
    </div>
{% endblock creat %}

templates/workspace/update.html
{% extends "workspace/base.html" %}

{% block creat %}
    <div class="container">
        <div class='flex items-center justify-center mt-5 mb-[50px]'>
            <form action="{% url 'update' id=courses.id %}" method="POST" enctype="multipart/form-data" class='w-full max-w-2xl bg-white p-8 rounded-lg shadow-lg' novalidate>
              {% csrf_token %}
              <h2 class="text-2xl font-bold text-center text-gray-700 mb-6">Изменение</h2>
              <div>
                <label for="id_title" >{{form.title.label}}</label>
                {{form.title}}
                <div class="text-danger">
                  {% for error in form.title.errors %}
                      <div class='text-red-500'>{{ error }}</div>
                  {% endfor %}
                </div>
              </div>
        
              <div>
                <label for="id_photo">{{form.photo.label}}</label>
                {{form.photo}}
                <div class="text-danger">
                  {% for error in form.photo.errors %}
                      <div class='text-red-500'>{{ error }}</div>
                  {% endfor %}
                </div>
              </div>
        
              <div>
                <label for="id_category">{{form.category.label}}</label>
                {{form.category}}
                <div class="text-danger">
                  {% for error in form.category.errors %}
                      <div class='text-red-500'>{{ error }}</div>
                  {% endfor %}
                </div>
              </div>
        
              <div>
                <label for="id_description">{{form.description.label}}</label>
                {{form.description}}
                <div class="text-danger">
                  {% for error in form.description.errors %}
                      <div class='text-red-500'>{{ error }}</div>
                  {% endfor %}
                </div>
              </div>
        
              <div>
                <label for="id_price">{{form.price.label}}</label>
                {{form.price}}
                <div class="text-danger">
                  {% for error in form.price.errors %}
                      <div class='text-red-500'>{{ error }}</div>
                  {% endfor %}
                </div>
              </div>
        
              <div>
                <label for="id_type_of_training">{{form.type_of_training.label}}</label>
                {{form.type_of_training}}
                <div class="text-danger">
                  {% for error in form.type_of_training.errors %}
                      <div class='text-red-500'>{{ error }}</div>
                  {% endfor %}
                </div>
              </div>
        
              <div>
                <label for="id_school">{{form.school.label}}</label>
                {{form.school}}
                <div class="text-danger">
                  {% for error in form.school.errors %}
                      <div class='text-red-500'>{{ error }}</div>
                  {% endfor %}
                </div>
              </div>
        
              <div>
                <label for="id_type_of_courses">{{form.type_of_courses.label}}</label>
                {{form.type_of_courses}}
                <div class="text-danger">
                  {% for error in form.type_of_courses.errors %}
                      <div class='text-red-500'>{{ error }}</div>
                  {% endfor %}
                </div>
              </div>
        
              <div>
                <label for="id_duration">{{form.duration.label}}</label>
                {{form.duration}}
                <div class="text-danger">
                  {% for error in form.duration.errors %}
                      <div class='text-red-500'>{{ error }}</div>
                  {% endfor %}
                </div>
              </div>
        
              <div>
                <label for="id_residence">{{form.residence.label}}</label>
                {{form.residence}}
                <div class="text-danger">
                  {% for error in form.residence.errors %}
                      <div class='text-red-500'>{{ error }}</div>
                  {% endfor %}
                </div>
              </div>
        
              <div class='mb-[20px]'>
                <label for="id_is_publish">{{form.is_publish.label}}</label>
                {{form.is_publish}}
                <div class="text-danger">
                  {% for error in form.is_publish.errors %}
                      <div class='text-red-500'>{{ error }}</div>
                  {% endfor %}
                </div>
              </div>
        
              <button type="submit" class="w-full py-3 bg-[#4361EE] text-white font-semibold rounded-lg hover:bg-[#4361EE] focus:outline-none focus:ring-2 focus:ring-black focus:ring-offset-2">Изменить</button>
            </form>
          </div>
    </div>
{% endblock creat %}